### PR TITLE
add md5 hex digest transformer

### PR DESCRIPTION
**Pull request by 7sDream**
This PR will:

- Keep old MD5+base64 transformer no change.
- Add MD5+Hex transformer
- Fix npm audit packages
- Close Issue #40

---

Screen record(1.1M):

image

### CODE REVIEW

**Comment by 7sDream** [comment]
The first CI failed due to the npm package audit, the second commit fixed it, I think.

And the second CI failure is due to some other reason which I don't understand. You can check it and tell me how to fix it, or just run it again and maybe it will pass.

This PR will close #40.

**Comment by mitchdenny** [comment]
I merged in some changes to update package dependencies and its introduced a conflict, can you rebase off master?

**Comment by 7sDream** [comment]
Done rebase.

**Comment by mitchdenny** [comment]
Thanks for the contribution @7sDream!

**Pull request merged**
